export class invoicePenalties {
    approvalDate: string
    clinicTypeCode: string
    clinicTypeId: number
    code: string
    createdBy: null
    createdDate: string
    date: string
    districtCode: string
    districtId: number
    districtName: string
    docRefNo: null
    fin02RefNo: null
    fin02Status: null
    fin03RefNo: null
    fin03Status: null
    //inner model
    //fin09Clinic: [{…}]
    id: number
    month: string
    remarks: null
    stateCode: string
    stateId: number
    stateName: string
    status: string
    totalLateDeliveryPenalty: number
    totalPenalty: number
    totalRepairTimePenalty: number
    totalResponseTimePenalty: number
    totalScheduledMaintenancePenalty: number
    totalUptimePenalty: number
    updatedBy: null
    updatedDate: string
    year: string
    circleCode: string
    quater: string
    monthName: string
    totalPenaltyPermanent: any;
}